name: VeeR-EL2 CI

on:
  push:
    branches: ["main"]
  pull_request:
  workflow_dispatch:

jobs:

  Build-Verilator:
    name: Build-Verilator
    uses: ./.github/workflows/build-verilator.yml

  Build-Spike:
    name: Build-Spike
    uses: ./.github/workflows/build-spike.yml

  Test-Regression:
    name: Test-Regression
    needs: [Build-Verilator]
    uses: ./.github/workflows/test-regression.yml

  Test-Verification:
    name: Test-Verification
    needs: [Build-Verilator]
    uses: ./.github/workflows/test-verification.yml

  Test-Microarchitectural:
    name: Test-Microarchitectural
    needs: [Build-Verilator]
    uses: ./.github/workflows/test-uarch.yml

  Test-RISCV-DV:
    name: Test-RISCV-DV
    needs: [Build-Verilator, Build-Spike]
    uses: ./.github/workflows/test-riscv-dv.yml

  Test-RISCOF:
    name: Test-RISCOF
    needs: [Build-Verilator, Build-Spike]
    uses: ./.github/workflows/test-riscof.yml

  Report-Coverage:
    name: Report-Coverage
    needs: [Test-Regression, Test-Verification, Test-RISCV-DV, Test-RISCOF]
    uses: ./.github/workflows/report-coverage.yml

  Publish-to-GH-Pages:
    concurrency:
      group: concurrency-group-${{ github.repository }}-publish
      cancel-in-progress: false
    permissions:
      actions: write
      contents: write
    name: Publish-to-GH-Pages
    needs: [Report-Coverage, Test-Verification]
    uses: ./.github/workflows/publish-webpage.yml
