name: GH-Pages PR Remove

on:
  pull_request:
    types:
      - closed

jobs:
  build:
    name: PR Remove
    concurrency:
      group: gh-pages
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

      - name: Save PR number
        run: |
          echo "number=${{ github.event.number }}" >> delete_pr_number.txt

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: delete_pr_number
          path: ./delete_pr_number.txt